name = 'alt:V Server'
debug = true
host = '0.0.0.0'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'b932ca4d-b033-462f-8de1-561fa9f0a80f'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['js-module', 'js-bytecode-module']
resources = ['weapon-addon', 'vehicle-addon', 'chat', 'admin', 'gangwar', 'anims', 'streetnames', 'wasted', 'pickups', 'players-list', 'veh-spawner', 'speedometer', 'hitmarker']

# Define the map bound size
mapBoundsMinX = -10000
mapBoundsMinY = -10000
mapBoundsMaxX = 65536
mapBoundsMaxY = 65536
mapCellAreaSize = 100 #smaller areas uses more ram and less cpu

[voice]
streamingTickRate = 10
# The bitrate of the voice server
bitrate = 64000
# The secret for the external server (only needed when using externalHost)
# The secret must consist of numeric values only
externalSecret = 1234567890
# The external host address (leave 127.0.0.1, if voice-server is on same machine)
externalHost = "127.0.0.1"
# The external host port
externalPort = 7798
# The external host public address (should be the ip address of your server, not localhost!)
externalPublicHost = "178.20.46.43"
# The external host public port
externalPublicPort = 7799